export const SUPERADMIN = 'SUPERADMIN'
export const ADMIN = 'ADMIN'
export const SUPERVISOR = 'SUPERVISOR'
export const EMPLEADO = 'EMPLEADO'
export const EXTERNO = 'EXTERNO'
export const USUARIO = 'USUARIO'
export const INVITADO = 'INVITADO'
export const TESTER = 'TESTER'
